theme: minima
title: Programming stuff
author: lumpsoid
description: Welcome to our blog! Our main focus is to provide guides and tutorials on configuring programs on Arch Linux, as well as sharing useful and simple code snippets for a variety of themes.
