theme: minima
#title: At the table with the data eater
#author: data eater
#description: Hello friend! Our main focus is to provide guides and tutorials on configuring programs on Arch Linux, as well as sharing useful and simple code snippets for a variety of themes.
